openapi: 3.0.0

info:
  title: Reactive API
  description: Reactive API documentation
  contact:
    name: Martin Mühlemann
  version: 0.1.0

servers:
  - url: /api/v1
    description: Current host
  - url: http://localhost:8080/api/v1
    description: Local development environment

components:
  schemas:
    Task:
      required:
        - id
        - title
        - creation
      properties:
        id:
          type: string
        title:
          type: string
        creation:
          type: string
          format: date-time